[tool.poetry]
name = "todo-list"
version = "0.1.0"
description = "A command-line ToDo list application with PostgreSQL persistence"
authors = ["Younes Kazemi M. <ykazemim04@gmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = ">=3.12"
python-dotenv = "^1.1.1"
sqlalchemy = "^2.0.0"
psycopg2-binary = "^2.9.0"
alembic = "^1.13.0"
schedule = "^1.2.0"
fastapi = "^0.124.0"
uvicorn = {extras = ["standard"], version = "^0.38.0"}

[tool.poetry.scripts]
todolist = "src.cli.__main__:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
