import os
from dotenv import load_dotenv

load_dotenv()

MAX_NUMBER_OF_PROJECTS = int(os.getenv("MAX_NUMBER_OF_PROJECTS", 10))
MAX_NUMBER_OF_TASKS_PER_PROJECT = int(os.getenv("MAX_NUMBER_OF_TASKS_PER_PROJECT", 50))

MAX_PROJECT_NAME_WORDS = int(os.getenv("MAX_PROJECT_NAME_WORDS", 30))
MAX_PROJECT_DESCRIPTION_WORDS = int(os.getenv("MAX_PROJECT_DESCRIPTION_WORDS", 150))
MAX_TASK_TITLE_WORDS = int(os.getenv("MAX_TASK_TITLE_WORDS", 30))
MAX_TASK_DESCRIPTION_WORDS = int(os.getenv("MAX_TASK_DESCRIPTION_WORDS", 150))
